-- Migration for tasks object
CREATE TABLE IF NOT EXISTS tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone not null,
    done_date timestamp with time zone
);
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- Foreign key
ALTER TABLE tasks ADD CONSTRAINT tasks_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id);

-- RLS policy: allow all authenticated users to select
CREATE POLICY "Allow select for authenticated" ON tasks FOR SELECT USING (auth.role() = 'authenticated');

-- Add FKs and indexes as needed 