-- Migration for dealNotes object
CREATE TABLE IF NOT EXISTS dealNotes (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[],
    summary text,
    sentiment text
);
ALTER TABLE dealNotes ENABLE ROW LEVEL SECURITY;

-- Foreign keys
ALTER TABLE dealNotes ADD CONSTRAINT dealNotes_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id);
ALTER TABLE dealNotes ADD CONSTRAINT dealNotes_sales_id_fkey FOREIGN KEY (sales_id) REFERENCES sales(id);

-- RLS: allow all authenticated users to view/manage all deal notes
CREATE POLICY "Authenticated users can view all deal notes" ON dealNotes FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can manage all deal notes" ON dealNotes FOR ALL USING (auth.role() = 'authenticated');

-- Add FKs and indexes as needed 