-- Migration for sales object
CREATE TABLE IF NOT EXISTS sales (
    id bigint generated by default as identity primary key,
    first_name text not null,
    last_name text not null,
    email text not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default FALSE
);
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;

-- Unique index on email
CREATE UNIQUE INDEX IF NOT EXISTS sales_email_key ON sales(email);

-- RLS: admin can select/update all, others only their own row
CREATE POLICY "Admins can access all" ON sales FOR ALL USING (administrator = true);
CREATE POLICY "Users can access their row" ON sales FOR ALL USING (auth.uid() = user_id);

-- Add FKs and indexes as needed 