-- Communication Logs table
CREATE TABLE IF NOT EXISTS communication_logs (
    id bigint generated by default as identity primary key,
    lead_id bigint not null,
    type text,
    direction text,
    content text,
    status text,
    timestamp timestamp with time zone not null default now(),
    sales_id bigint
); 