-- Migration for contactNotes object
CREATE TABLE IF NOT EXISTS contactNotes (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[],
    summary text,
    sentiment text
);
ALTER TABLE contactNotes ENABLE ROW LEVEL SECURITY;
-- Add FKs and indexes as needed 

-- RLS: allow all authenticated users to view/manage all contact notes
CREATE POLICY "Authenticated users can view all contact notes" ON contactNotes FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can manage all contact notes" ON contactNotes FOR ALL USING (auth.role() = 'authenticated'); 