-- Calendar Integrations table
CREATE TABLE IF NOT EXISTS calendar_integrations (
    id bigint generated by default as identity primary key,
    sales_id bigint not null,
    provider text not null,
    access_token text,
    refresh_token text,
    expires_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

-- Calendar Events table
CREATE TABLE IF NOT EXISTS calendar_events (
    id bigint generated by default as identity primary key,
    integration_id bigint not null,
    external_id text,
    title text,
    description text,
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    location text,
    attendees jsonb,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
); 