-- Campaigns table
CREATE TABLE IF NOT EXISTS campaigns (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    type text,
    status text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint
);

-- Sequences table
CREATE TABLE IF NOT EXISTS sequences (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    steps jsonb,
    status text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint
);

-- Templates table
CREATE TABLE IF NOT EXISTS templates (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    type text,
    subject text,
    content text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint
); 