-- Migration for companies object
CREATE TABLE IF NOT EXISTS companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website text,
    phone_number text,
    address text,
    zipcode text,
    city text,
    stateAbbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb,
    external_id text,
    founded_year integer
);

ALTER TABLE companies ENABLE ROW LEVEL SECURITY;

-- Foreign key to sales
ALTER TABLE companies ADD CONSTRAINT companies_sales_id_fkey FOREIGN KEY (sales_id) REFERENCES sales(id);

-- Unique index on name
CREATE UNIQUE INDEX IF NOT EXISTS companies_name_key ON companies(name);

-- RLS policy: allow all authenticated users to select
CREATE POLICY "Allow select for authenticated" ON companies FOR SELECT USING (auth.role() = 'authenticated');

-- Add FKs and indexes as needed 