-- Migration for tags object
CREATE TABLE IF NOT EXISTS tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;

-- Unique index on name
CREATE UNIQUE INDEX IF NOT EXISTS tags_name_key ON tags(name);

-- RLS policy: allow all authenticated users to select
CREATE POLICY "Allow select for authenticated" ON tags FOR SELECT USING (auth.role() = 'authenticated');

-- Add FKs and indexes as needed 