-- Migration for deals object
CREATE TABLE IF NOT EXISTS deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone default null,
    expected_closing_date timestamp with time zone default null,
    sales_id bigint,
    index smallint
);
ALTER TABLE deals ENABLE ROW LEVEL SECURITY;

-- Foreign keys
ALTER TABLE deals ADD CONSTRAINT deals_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE deals ADD CONSTRAINT deals_sales_id_fkey FOREIGN KEY (sales_id) REFERENCES sales(id);

-- Unique index on name
CREATE UNIQUE INDEX IF NOT EXISTS deals_name_key ON deals(name);

-- RLS: allow all authenticated users to view/manage all deals
CREATE POLICY "Authenticated users can view all deals" ON deals FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can manage all deals" ON deals FOR ALL USING (auth.role() = 'authenticated');

-- Add FKs and indexes as needed 