-- Migration for contacts object
CREATE TABLE IF NOT EXISTS contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    email text,
    email_jsonb jsonb,
    phone_1_number text,
    phone_1_type text,
    phone_2_number text,
    phone_2_type text,
    phone_jsonb jsonb,
    background text,
    acquisition text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    external_id text
);

ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- Foreign keys
ALTER TABLE contacts ADD CONSTRAINT contacts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE contacts ADD CONSTRAINT contacts_sales_id_fkey FOREIGN KEY (sales_id) REFERENCES sales(id);

-- Unique index on email
CREATE UNIQUE INDEX IF NOT EXISTS contacts_email_key ON contacts(email);

-- RLS: allow all authenticated users to view/manage all contacts
CREATE POLICY "Authenticated users can view all contacts" ON contacts FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can manage all contacts" ON contacts FOR ALL USING (auth.role() = 'authenticated');

-- Add FKs and indexes as needed 